apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}

  {% set items = ${{values.templateVersion}} %}
  {% endset %}
  {% for each in items %}
  tags: <li>{{ each }}</li>
  {% endfor %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}